// <auto-generated />
namespace SEPBankingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-rc1-20726")]
    public sealed partial class bankaccount_transactionhistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bankaccount_transactionhistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201310231259459_bankaccount_transactionhistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
